import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { Navbar } from "~/components";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Timetable",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} flex`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
``;
